# base image
FROM node:10.16-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
COPY proxy.conf.json /app/proxy.config.json
RUN npm install
RUN npm install -g @angular/cli@9.1.1

# add app
COPY . /app

# start app
CMD ng serve --host 0.0.0.0